Test admin services
Star-Academy/Summer1403-Project-Group03-Backend pull request #79
Opened 2024-09-02 18:26 UTC by K-Kabiri

2024-09-03 18:48 UTC, mahdijafariii requested changes
اینا خواهشا اوکی کنید
بقیش ک بنظر خوب بود ولی کانفلیکت هم دارید

2024-09-04 07:55 UTC, mahdijafariii approved these changes

2024-09-04 11:18 UTC, merged

2024-09-04 11:53 UTC, K-Kabiri commented on AnalysisData/TestProject/User/Services/AdminService/AdminServiceTests.cs
> +                Email = "email1@gmail.com", PhoneNumber = "09111111111", Role = new Role { RoleName = "Admin" }
برای ساخت یه یوزر نیازه دیگ چیکارش میخواین بکنین؟

2024-09-04 11:54 UTC, K-Kabiri commented on AnalysisData/TestProject/User/Services/AdminService/AdminRegisterServiceTests.cs
> +        var action = () => _sut.RegisterByAdminAsync(userRegisterDto);
خودشون یاد دادن نوشتن اکشن رو 
علی ابراهیمی توی کارگاهش گفت برای اکسپشن ها و ما داخل پروژه قبلیمونم نوشتیم و اوکیه

2024-09-04 11:54 UTC, K-Kabiri commented on AnalysisData/AnalysisData/Graph/Model/File/UserFile.cs
> +    [ForeignKey("UserId")] public User.Model.User User { get; set; }
چک میکنم